reduced comments and changed variable names for method grow
jaykay9999/jhotdrawreview pull request #1
Opened 2024-01-14 02:25 UTC by jaykay99992

The comment for method grow() was too lengthy so I reduced it. And I changed the variable names v and h to VE and HE to give a clearer abbreviation

2024-02-19 01:59 UTC, JFLeblay requested changes
Please change the code according to my comments so that I can approve the Pull Request.

2024-02-19 01:59 UTC, JFLeblay commented on jhotdraw-utils/src/main/java/org/jhotdraw/geom/Geom.java
> +  public static void grow(Rectangle2D.Double r, double HE, double VE) {
L'utilisation de majuscule en Java est réservé aux constantes. Dans votre cas, vous devriez utiliser un nom de paramètre significatif comme horizontalExpansion et verticalExpansion. Cela améliore la lisibilité et permettra au programmeur de comprendre la fonction de chaque paramètre sans avois à lire la documentation.

2024-02-19 15:07 UTC, jaykay99992 commented
@JFLeblay I just updated the variable names as you mentioned to represent what they do clearly. Is it fine like this ? Do i merge it like this ?

2024-02-19 15:12 UTC, JFLeblay commented on jhotdraw-utils/src/main/java/org/jhotdraw/geom/Geom.java
> +   * <p>The new Rectangle2D.Double grows is if HE and VE are positive,
Please make sure you use meaning names and not abbreviations for HE and VE

2024-02-19 15:12 UTC, JFLeblay commented on jhotdraw-utils/src/main/java/org/jhotdraw/geom/Geom.java
> +   * <p>If negative values are supplied for HE and VE, the size of the Rectangle2D decreases
Please make sure you use meaning names and not abbreviations for HE and VE

2024-02-19 15:14 UTC, JFLeblay requested changes
When you are refactoring, please make sure the documentation reflects your changes. In your case, you have not replace HE and VE with meaningful names in the documentation.

2024-02-20 15:25 UTC, jaykay99992 commented
@JFLeblay yeaa my bad, didn't see those. I just updated them too. Should I merge it like this now ?

2024-02-20 16:50 UTC, JFLeblay approved these changes
No problem.
You're good now. Please merge.

2024-02-21 00:20 UTC, merged

2024-02-21 00:20 UTC, jaykay9999 commented
good job, code merged