Added comments for methods
jaykay9999/jhotdrawreview pull request #13
Opened 2024-01-14 16:54 UTC by jaykay99992

the FigureListenerAdapter class overrides the FigureListener methods, but it lacks the comments for what each method does. So I imported them from the FigureListener to avoid jumping from files just to read comments.

2024-02-09 20:28 UTC, RobinHermet requested changes
Les commentaires de documentation (JavaDocs) écrits au-dessus des méthodes dans une classe parente ou interface sont automatiquement hérités par les classes enfants qui les surchargent (override). Quand on survole le nom d'une méthode qui override une méthode de la classe parente dans la plupart des IDE, le commentaire de documentation de la méthode parente s'affiche généralement.
Il serait donc préférable d'utiliser les tags JavaDoc appropriés dans FigureListener pour fournir des informations plus détaillées. Par exemple :

/**
 * Sent when a figure is added to a drawing.
 * 
 * @param e the event object that characterizes the change.
 */
@Override
public void figureAdded(FigureEvent e) {}

Les commentaires actuels ne fournissent pas beaucoup plus d'informations que ce qui est déjà présenté par les noms des méthodes. Ils pourraient être rendus plus utiles en ajoutant des détails spécifiques sur les paramètres, les valeurs de retour attendues et les exceptions potentielles. En plus en ayant copier/coller comme tu l'as fait, si les commentaires de la classe parente ou de l'interface sont mis à jour, les commentaires dans la classe enfant ne seront pas mis à jour automatiquement, ce qui pourrait entraîner des incohérences.
Il est donc préférable de s'appuyer sur les fonctionnalités des IDE pour afficher la documentation héritée afin de réduire la redondance et les besoins en maintenance.

2024-02-09 20:37 UTC, jaykay99992 commented
Donc, je vais simplement le laisser tel quel et rejeter la pull request pour le maintenir en l'état et utiliser uniquement les commentaires de la classe parente

2024-02-09 21:13 UTC, RobinHermet commented
Oui cela me semble être une bonne solution.

2024-02-10 18:16 UTC, closed without merging

2024-02-10 18:17 UTC, jaykay9999 commented
Rejeté la demande de fusion pour conserver le même style de commentaire initial.