Refactored getPenpendicularFillGrowth() for simplicity
jaykay9999/jhotdrawreview pull request #7
Opened 2024-01-14 12:45 UTC by jaykay99992

Refactored getPenpendicularFillGrowth() through adding a reusable function growthCalculation()

2024-02-19 02:23 UTC, JFLeblay commented on jhotdraw-core/src/main/java/org/jhotdraw/draw/AttributeKeys.java
> +        grow = growthCalculation(placement, strokeWidth);
In this situation, growthCalculation will NOT return what you expect

2024-02-19 02:24 UTC, JFLeblay commented on jhotdraw-core/src/main/java/org/jhotdraw/draw/AttributeKeys.java
> +        grow = growthCalculation(placement, strokeWidth);
Same comment as before

2024-02-19 02:38 UTC, JFLeblay requested changes
Whereas it is a good idea to try to refactor duplicate switch statements, the changes you have implemented are indeed changing the behavior of your method getPerpendicularFillGrowth. Now, after refactoring, the method getPerpendicularFillGrowth will always return the same value of grow regardless of the value in STROKE_PLACEMENT.
I cannot approve this Pull Request as it is. 
If you want to make the method getPerpandicularFillGrowth shorter, you could extract each `switch (placement)` into a separate method.

2024-02-19 15:03 UTC, jaykay99992 commented
@JFLeblay I just refactored the code even more through treating each case of FILL_UNDER_STROKE in a separate method, is it fine like this ? do I merge it , or just reject the whole pull request if you think it became much more complicated ?

2024-02-19 15:03 UTC, JFLeblay approved these changes
Now the behovior is not altered and your code is cleaner.
You can merge it.

2024-02-20 15:20 UTC, merged

2024-02-20 15:21 UTC, jaykay9999 commented
Sure, code merged